### PR TITLE
Expand aurelius functionality

### PR DESCRIPTION
**Pull request by ReportMort**
The purpose of this pull request is to expand functionality in `aurelius` (R package). More specifically, the model producers in the package, along with basic scaffolding of a typical R package such as Travis CI and Codecov YAML files so that future iterations of the package build can be more closely monitored.

A vignette has been created that outlines the major functionality changes introduced by these commits: 
https://cdn.rawgit.com/ReportMort/hadrian/feature/add-r-package-structure/aurelius/vignettes/migration-to-new-syntax.html

### CODE REVIEW

**Comment by jpivarski** [comment]
Thank you very much! This is a huge amount of work. We're testing it and will get back to you shortly.

**Comment by ReportMort** [comment]
Hey @jpivarski, any thoughts, concerns, questions on this? I was just going to keep adding new model producers but wanted to pause for any feedback on your end.

**Comment by jpivarski** [comment]
Oh, please don't hold it up on my account. I've been following this and I
approve. It was my intention that it should grow in this way.

Jim





On Apr 2, 2017 1:11 PM, "Steve Mortimer" <notifications@github.com> wrote:

Hey @jpivarski <https://github.com/jpivarski>, any thoughts, concerns,
questions on this? I was just going to keep adding new model producers but
wanted to pause for any feedback on your end.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/opendatagroup/hadrian/pull/32#issuecomment-291003723>,
or mute the thread

**Comment by ReportMort** [comment]
@jpivarski We're now on CRAN with these updates, https://CRAN.R-project.org/package=aurelius.

Do you think we could review, merge, and close this PR? I was thinking we could start a separate thread to continue expanding functionality.

**Comment by ReportMort** [comment]
@mahowald-odg Putting this on your radar. Jim P. mentioned you were in charge of managing Hadrian/Titus/Aurelius releases.

**Comment by mahowald-odg** [comment]
Thanks for all the work, @ReportMort , this is great!

**Pull request merged**
